

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id ("java")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    // Add Sonatype snapshots repo for TamboUI
    maven {
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
        mavenContent {
            snapshotsOnly()
        }
    }
}

dependencies {
    implementation(platform("dev.tamboui:tamboui-bom:0.5.0-SNAPSHOT"))

    // For Toolkit DSL (recommended)
    implementation("dev.tamboui:tamboui-toolkit")

    // JLine backend (required)
    implementation("dev.tamboui:tamboui-jline3-backend")

    testImplementation("org.junit.jupiter:junit-jupiter:6.1.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")    
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


application {
    // Define the main class for the application.
    mainClass = "com.example.Main"
    
    tasks.named<JavaExec>("run") {

        standardInput = System.`in`

    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
