

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    java
    `maven-publish`
    id("com.gradleup.shadow") version "9.0.0"
}



repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    // Add Sonatype snapshots repo for TamboUI
    maven {
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
        mavenContent {
            snapshotsOnly()
        }
    }
}

dependencies {
    implementation(platform("dev.tamboui:tamboui-bom:0.5.0-SNAPSHOT"))

    // For Toolkit DSL (recommended)
    implementation("dev.tamboui:tamboui-toolkit")

    // JLine backend (required)
    implementation("dev.tamboui:tamboui-jline3-backend")

    testImplementation("org.junit.jupiter:junit-jupiter:6.1.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")  

    // Jsoup implementation
    implementation("org.jsoup:jsoup:1.22.1")

    // Jackson JSON Processing Library implementation
    implementation("com.fasterxml.jackson.core:jackson-databind:2.22.0")
  

    // Core Lucene library
    implementation("org.apache.lucene:lucene-core:9.12.2")

    // Analyzers for common languages and token filters
    implementation("org.apache.lucene:lucene-analysis-common:9.12.2")

    // Query parser
    implementation("org.apache.lucene:lucene-queryparser:9.12.2")

    // ascii table for rendering html tables
    implementation("de.vandermeer:asciitable:0.3.2")

}


// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

group = "io.github.nazeermazeer"
version = "1.0.0"


application {
    mainClass = "com.example.Main"
}

tasks.jar {
    manifest {
        attributes[
            "Main-Class"
        ] = application.mainClass.get()
    }
}

tasks.shadowJar {
    archiveClassifier.set("all")
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Ensure Java vector incubator module is run
tasks.run {
    jvmArgs("--add-modules=jdk.incubator.vector")
}

tasks.withType<JavaExec>().configureEach {
    jvmArgs("--add-modules", "jdk.incubator.vector")
}

publishing {
    publications {
        create<MavenPublication>("gpr") {
            from(components["java"])
            artifact(tasks.shadowJar)
            groupId = project.group.toString()
            artifactId = "whiz"
            version = project.version.toString()
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/nazeermazeer/whiz")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
